[package]
name = "peridio-cli"
description = "Peridio CLI"
homepage = "https://peridio.com"
repository = "https://github.com/peridio/morel"
version = "0.1.0"
edition = "2021"

[dependencies]
peridio-sdk = { git = "ssh://git@github.com/peridio/reishi.git", rev = "7a0c59c" }
serde_json = "1.0"
snafu = "0.7"
structopt = "0.3"
tokio = { version = "1.4", features = ["full"] }
tower = {version = "0.4"}
