[package]
name = "peridio-cli"
description = "Peridio CLI"
homepage = "https://peridio.com"
repository = "https://github.com/peridio/morel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peridio-sdk = { git = "ssh://git@github.com/peridio/reishi.git", rev = "f5a6682"}
structopt = "0.3"
tokio = { version = "1.4", features = ["full"] }
tonic = {version = "0.6", features = ["compression"]}
tower = {version = "0.4"}
